import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { UserSummaryHealthStatusContextProvider } from "@/contexts/userSummary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anti Sheet Nutrition",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserSummaryHealthStatusContextProvider>
        <head></head>
        <body className={inter.className}>
          <Theme>{children}</Theme>
        </body>
      </UserSummaryHealthStatusContextProvider>
    </html>
  );
}
